version: "3.8"
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_REACT_APP_API_URL: http://backend:5000/api/
    networks:
      - my-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      DB_CONNECTION: "Server=sql-server,1433;Initial Catalog=Test1;User Id=sa;Password=YourPassword123!;Encrypt=False;"
      CORS: "http://frontend:5173"
    networks:
      - my-network

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourPassword123!
    ports:
      - "1433:1433"
    # volumes:
    #   - sql-data:/var/opt/mssql
    networks:
      - my-network

# volumes:
#   sql-data:

networks:
  my-network:
